#!/bin/bash
set -euo pipefail
shopt -s inherit_errexit
WD="$(realpath $(dirname $0))"

label() { echo "rootless-netns-hostbridge-examples"; }
dhcp_name() { echo "$(label)-dhcp"; }
qemu_name() { echo "$(label)-qemu"; }
rootless_netns_if_id() { podman unshare --rootless-cni ip link show $1 |grep --max-count 1 -Eo '^[0-9]+'; }
list_of_labeled_containers() { podman container ps --no-trunc --format "{{ .ID }}" --filter label=`label`; }

dhcp_logs_tail() {
	podman logs \
		--tail 0 \
		--follow \
		`dhcp_name` \
		2>&1
}

exit_after_dhcpack() {
	while read LINE; do
		echo "$LINE"
		[[ "$LINE" =~ "DHCPACK" ]] || continue
		podman container stop `list_of_labeled_containers`
		podman unshare --rootless-cni ip link delete macvtap0 \
			&>/dev/null \
			|| true
		kill -s SIGTERM $$ # `podman logs` doesn't exit otherwise
	done
}

example_dhcp() {
	network_gateway_address() {
		podman network inspect "$1" \
			|grep '"gateway":' \
			|grep -Eo '[0-9.]+",?$' \
			|grep -Eo '[0-9.]+'
	}
	dhcp_gateway() { network_gateway_address "$1"; }
	dhcp_gateway_net() { F=$(network_gateway_address "$1"); echo "${F%.*}."; }
	dhcp_range_from() { echo "$(dhcp_gateway_net "$1")200"; }
	dhcp_range_to() { echo "$(dhcp_gateway_net "$1")210"; }
	example_name() { dhcp_name; }
	podman build \
		--target dhcp \
		--tag `example_name` \
		examples
	podman stop `example_name` \
		&>/dev/null \
		|| true
	podman run \
		--cap-add NET_ADMIN,NET_RAW \
		--detach \
		--entrypoint "" \
		--label `label` \
		--name `example_name` \
		--network "$1" \
		--rm \
		`example_name` \
		dnsmasq \
			--dhcp-option=option:router,`dhcp_gateway "$1"` \
			--dhcp-range=`dhcp_range_from "$1"`,`dhcp_range_to "$1"` \
			--dhcp-option=\#undi,option:bootfile-name,mock.kpxe \
			--dhcp-option=\#undi,option:tftp-server,0.0.0.0 \
			--dhcp-userclass=set:pxe,PXEClient \
			--interface="eth0" \
			--log-dhcp \
			--no-daemon \
			--port 0
}

example_qemu() {
	example_name() { qemu_name; }
	podman unshare --rootless-cni \
		ip link delete macvtap0 \
		&>/dev/null \
		|| true
	podman unshare --rootless-cni \
		ip link add \
			macvtap0 \
			link `podman network inspect "$1" --format '{{ (index .plugins 0).bridge }}'` \
			address 00:12:12:00:00:01 \
			type macvtap \
			mode bridge
	podman unshare --rootless-cni ip link set macvtap0 up
	sudo chown `id -u`:`id -g` "/dev/tap$(rootless_netns_if_id macvtap0)"
	podman build \
		--target qemu \
		--tag `example_name` \
		examples
	podman stop `example_name` \
		&>/dev/null \
		|| true
	podman run \
		--detach \
		--label `label` \
		--name `example_name` \
		--network none \
		--privileged \
		--rm \
		-it \
		-v /dev/tap`rootless_netns_if_id macvtap0`:/dev/tap0 \
		`example_name`
}

example_qemu_dhcp() {
	sudo --validate
	example_dhcp "$1"
	example_qemu "$1"
	dhcp_logs_tail |exit_after_dhcpack
}

example_host_interface_dhcp() {
	$WD/rootless-netns-hostbridge "$1" "$2"
	example_dhcp "$1"
	dhcp_logs_tail |exit_after_dhcpack
}

case "${1:-}" in
	qemu_dhcp)
		shift
		example_qemu_dhcp $*
		;;
	host_interface_dhcp)
		shift
		example_host_interface_dhcp $*
		;;
	"")
		echo "usage: example [example-name] ..."
		;;
	*)
		echo "example $1 does not exist"
		;;
esac
